"""Cookie helpers: Netscape file <-> header string, browser probe."""

from __future__ import annotations

import os
import time
from typing import Iterable, Optional


def parse_netscape_cookies(path: str, domain_substr: str = "") -> dict[str, str]:
    """Parse Netscape cookies.txt into name->value (last wins)."""
    out: dict[str, str] = {}
    if not path or not os.path.isfile(path):
        return out
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 7:
                continue
            domain, _flag, _path, _secure, _expires, name, value = parts[:7]
            if domain_substr and domain_substr not in domain:
                continue
            if name:
                out[name] = value
    return out


def cookies_to_header(cookies: dict[str, str]) -> str:
    return "; ".join(f"{k}={v}" for k, v in cookies.items() if k and v is not None)


def write_netscape_cookies(path: str, cookies: Iterable[dict]) -> None:
    """Write Playwright/browser cookie dicts to Netscape file."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by LinkFetch"]
    now = int(time.time())
    for c in cookies:
        domain = c.get("domain") or ""
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        cpath = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        exp = c.get("expires")
        try:
            exp_i = int(exp) if exp is not None else 0
        except (TypeError, ValueError):
            exp_i = 0
        if exp_i < 0:
            exp_i = now + 30 * 86400
        name = c.get("name") or ""
        value = (c.get("value") or "").replace("\n", "").replace("\r", "")
        if not name:
            continue
        lines.append(
            "\t".join([domain, flag, cpath, secure, str(exp_i), name, value])
        )
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def try_browser_cookie_header(browser: str, domain: str) -> Optional[str]:
    """Best-effort read cookies via browser_cookie3. Returns header or None."""
    try:
        import browser_cookie3
    except Exception:
        return None
    fn = {
        "firefox": getattr(browser_cookie3, "firefox", None),
        "chrome": getattr(browser_cookie3, "chrome", None),
        "edge": getattr(browser_cookie3, "edge", None),
        "brave": getattr(browser_cookie3, "brave", None),
    }.get((browser or "").lower())
    if not fn:
        return None
    try:
        jar = fn(domain_name=domain)
        cookies = {c.name: c.value for c in jar if c.name}
        return cookies_to_header(cookies) if cookies else None
    except Exception:
        return None
